DROP TABLE IF EXISTS "note";

CREATE TABLE "note" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  router VARCHAR(255),
  title VARCHAR(255) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME DEFAULT CURRENT_TIMESTAMP
);